package main

import (
	"github.com/aws-transfer-family/mcp-server/config"
	"github.com/aws-transfer-family/mcp-server/models"
	tools_x_amz_target_transferservice_deleteaccess "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_deleteaccess"
	tools_x_amz_target_transferservice_startfiletransfer "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_startfiletransfer"
	tools_x_amz_target_transferservice_untagresource "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_untagresource"
	tools_x_amz_target_transferservice_describeexecution "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_describeexecution"
	tools_x_amz_target_transferservice_stopserver "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_stopserver"
	tools_x_amz_target_transferservice_describeworkflow "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_describeworkflow"
	tools_x_amz_target_transferservice_deleteprofile "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_deleteprofile"
	tools_x_amz_target_transferservice_listaccesses "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_listaccesses"
	tools_x_amz_target_transferservice_describeprofile "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_describeprofile"
	tools_x_amz_target_transferservice_testidentityprovider "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_testidentityprovider"
	tools_x_amz_target_transferservice_deletesshpublickey "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_deletesshpublickey"
	tools_x_amz_target_transferservice_describeserver "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_describeserver"
	tools_x_amz_target_transferservice_listusers "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_listusers"
	tools_x_amz_target_transferservice_describehostkey "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_describehostkey"
	tools_x_amz_target_transferservice_describecertificate "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_describecertificate"
	tools_x_amz_target_transferservice_updateprofile "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_updateprofile"
	tools_x_amz_target_transferservice_createuser "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_createuser"
	tools_x_amz_target_transferservice_deleteuser "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_deleteuser"
	tools_x_amz_target_transferservice_listsecuritypolicies "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_listsecuritypolicies"
	tools_x_amz_target_transferservice_listhostkeys "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_listhostkeys"
	tools_x_amz_target_transferservice_updateserver "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_updateserver"
	tools_x_amz_target_transferservice_createworkflow "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_createworkflow"
	tools_x_amz_target_transferservice_listagreements "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_listagreements"
	tools_x_amz_target_transferservice_describeuser "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_describeuser"
	tools_x_amz_target_transferservice_deletecertificate "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_deletecertificate"
	tools_x_amz_target_transferservice_updateagreement "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_updateagreement"
	tools_x_amz_target_transferservice_updateaccess "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_updateaccess"
	tools_x_amz_target_transferservice_updateuser "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_updateuser"
	tools_x_amz_target_transferservice_sendworkflowstepstate "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_sendworkflowstepstate"
	tools_x_amz_target_transferservice_listconnectors "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_listconnectors"
	tools_x_amz_target_transferservice_describesecuritypolicy "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_describesecuritypolicy"
	tools_x_amz_target_transferservice_createserver "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_createserver"
	tools_x_amz_target_transferservice_deleteconnector "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_deleteconnector"
	tools_x_amz_target_transferservice_importhostkey "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_importhostkey"
	tools_x_amz_target_transferservice_startserver "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_startserver"
	tools_x_amz_target_transferservice_createaccess "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_createaccess"
	tools_x_amz_target_transferservice_deletehostkey "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_deletehostkey"
	tools_x_amz_target_transferservice_describeagreement "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_describeagreement"
	tools_x_amz_target_transferservice_updateconnector "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_updateconnector"
	tools_x_amz_target_transferservice_tagresource "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_tagresource"
	tools_x_amz_target_transferservice_testconnection "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_testconnection"
	tools_x_amz_target_transferservice_listworkflows "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_listworkflows"
	tools_x_amz_target_transferservice_describeaccess "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_describeaccess"
	tools_x_amz_target_transferservice_describeconnector "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_describeconnector"
	tools_x_amz_target_transferservice_listtagsforresource "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_listtagsforresource"
	tools_x_amz_target_transferservice_listcertificates "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_listcertificates"
	tools_x_amz_target_transferservice_createagreement "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_createagreement"
	tools_x_amz_target_transferservice_importsshpublickey "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_importsshpublickey"
	tools_x_amz_target_transferservice_updatecertificate "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_updatecertificate"
	tools_x_amz_target_transferservice_importcertificate "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_importcertificate"
	tools_x_amz_target_transferservice_deleteagreement "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_deleteagreement"
	tools_x_amz_target_transferservice_listprofiles "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_listprofiles"
	tools_x_amz_target_transferservice_createprofile "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_createprofile"
	tools_x_amz_target_transferservice_createconnector "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_createconnector"
	tools_x_amz_target_transferservice_deleteworkflow "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_deleteworkflow"
	tools_x_amz_target_transferservice_listservers "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_listservers"
	tools_x_amz_target_transferservice_deleteserver "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_deleteserver"
	tools_x_amz_target_transferservice_listexecutions "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_listexecutions"
	tools_x_amz_target_transferservice_updatehostkey "github.com/aws-transfer-family/mcp-server/tools/x_amz_target_transferservice_updatehostkey"
)

func GetAll(cfg *config.APIConfig) []models.Tool {
	return []models.Tool{
		tools_x_amz_target_transferservice_deleteaccess.CreateDeleteaccessTool(cfg),
		tools_x_amz_target_transferservice_startfiletransfer.CreateStartfiletransferTool(cfg),
		tools_x_amz_target_transferservice_untagresource.CreateUntagresourceTool(cfg),
		tools_x_amz_target_transferservice_describeexecution.CreateDescribeexecutionTool(cfg),
		tools_x_amz_target_transferservice_stopserver.CreateStopserverTool(cfg),
		tools_x_amz_target_transferservice_describeworkflow.CreateDescribeworkflowTool(cfg),
		tools_x_amz_target_transferservice_deleteprofile.CreateDeleteprofileTool(cfg),
		tools_x_amz_target_transferservice_listaccesses.CreateListaccessesTool(cfg),
		tools_x_amz_target_transferservice_describeprofile.CreateDescribeprofileTool(cfg),
		tools_x_amz_target_transferservice_testidentityprovider.CreateTestidentityproviderTool(cfg),
		tools_x_amz_target_transferservice_deletesshpublickey.CreateDeletesshpublickeyTool(cfg),
		tools_x_amz_target_transferservice_describeserver.CreateDescribeserverTool(cfg),
		tools_x_amz_target_transferservice_listusers.CreateListusersTool(cfg),
		tools_x_amz_target_transferservice_describehostkey.CreateDescribehostkeyTool(cfg),
		tools_x_amz_target_transferservice_describecertificate.CreateDescribecertificateTool(cfg),
		tools_x_amz_target_transferservice_updateprofile.CreateUpdateprofileTool(cfg),
		tools_x_amz_target_transferservice_createuser.CreateCreateuserTool(cfg),
		tools_x_amz_target_transferservice_deleteuser.CreateDeleteuserTool(cfg),
		tools_x_amz_target_transferservice_listsecuritypolicies.CreateListsecuritypoliciesTool(cfg),
		tools_x_amz_target_transferservice_listhostkeys.CreateListhostkeysTool(cfg),
		tools_x_amz_target_transferservice_updateserver.CreateUpdateserverTool(cfg),
		tools_x_amz_target_transferservice_createworkflow.CreateCreateworkflowTool(cfg),
		tools_x_amz_target_transferservice_listagreements.CreateListagreementsTool(cfg),
		tools_x_amz_target_transferservice_describeuser.CreateDescribeuserTool(cfg),
		tools_x_amz_target_transferservice_deletecertificate.CreateDeletecertificateTool(cfg),
		tools_x_amz_target_transferservice_updateagreement.CreateUpdateagreementTool(cfg),
		tools_x_amz_target_transferservice_updateaccess.CreateUpdateaccessTool(cfg),
		tools_x_amz_target_transferservice_updateuser.CreateUpdateuserTool(cfg),
		tools_x_amz_target_transferservice_sendworkflowstepstate.CreateSendworkflowstepstateTool(cfg),
		tools_x_amz_target_transferservice_listconnectors.CreateListconnectorsTool(cfg),
		tools_x_amz_target_transferservice_describesecuritypolicy.CreateDescribesecuritypolicyTool(cfg),
		tools_x_amz_target_transferservice_createserver.CreateCreateserverTool(cfg),
		tools_x_amz_target_transferservice_deleteconnector.CreateDeleteconnectorTool(cfg),
		tools_x_amz_target_transferservice_importhostkey.CreateImporthostkeyTool(cfg),
		tools_x_amz_target_transferservice_startserver.CreateStartserverTool(cfg),
		tools_x_amz_target_transferservice_createaccess.CreateCreateaccessTool(cfg),
		tools_x_amz_target_transferservice_deletehostkey.CreateDeletehostkeyTool(cfg),
		tools_x_amz_target_transferservice_describeagreement.CreateDescribeagreementTool(cfg),
		tools_x_amz_target_transferservice_updateconnector.CreateUpdateconnectorTool(cfg),
		tools_x_amz_target_transferservice_tagresource.CreateTagresourceTool(cfg),
		tools_x_amz_target_transferservice_testconnection.CreateTestconnectionTool(cfg),
		tools_x_amz_target_transferservice_listworkflows.CreateListworkflowsTool(cfg),
		tools_x_amz_target_transferservice_describeaccess.CreateDescribeaccessTool(cfg),
		tools_x_amz_target_transferservice_describeconnector.CreateDescribeconnectorTool(cfg),
		tools_x_amz_target_transferservice_listtagsforresource.CreateListtagsforresourceTool(cfg),
		tools_x_amz_target_transferservice_listcertificates.CreateListcertificatesTool(cfg),
		tools_x_amz_target_transferservice_createagreement.CreateCreateagreementTool(cfg),
		tools_x_amz_target_transferservice_importsshpublickey.CreateImportsshpublickeyTool(cfg),
		tools_x_amz_target_transferservice_updatecertificate.CreateUpdatecertificateTool(cfg),
		tools_x_amz_target_transferservice_importcertificate.CreateImportcertificateTool(cfg),
		tools_x_amz_target_transferservice_deleteagreement.CreateDeleteagreementTool(cfg),
		tools_x_amz_target_transferservice_listprofiles.CreateListprofilesTool(cfg),
		tools_x_amz_target_transferservice_createprofile.CreateCreateprofileTool(cfg),
		tools_x_amz_target_transferservice_createconnector.CreateCreateconnectorTool(cfg),
		tools_x_amz_target_transferservice_deleteworkflow.CreateDeleteworkflowTool(cfg),
		tools_x_amz_target_transferservice_listservers.CreateListserversTool(cfg),
		tools_x_amz_target_transferservice_deleteserver.CreateDeleteserverTool(cfg),
		tools_x_amz_target_transferservice_listexecutions.CreateListexecutionsTool(cfg),
		tools_x_amz_target_transferservice_updatehostkey.CreateUpdatehostkeyTool(cfg),
	}
}
